name: "SVG to PNG Converter"
version: "1.1.1"
# stage: "experimental"
slug: "svg_to_png"
description: "A Home Assistant add-on to convert SVG images to PNG."
url: "https://github.com/der-punkt/svg_to_png_addon/tree/main/addon"
startup: application
boot: auto
hassio_api: true  # Enable Home Assistant API access
hassio_role: "admin"
host_network: false  # Change to true if needed
ingress: false
arch:
  - aarch64
  - amd64
  - armv7
init: false
options:
  full_access: true
schema:
  full_access: bool?
privileged:
  - "ALL"  # Grants full privileged access (use with caution)